export const GAME = Object.freeze({
  WIDTH: 1920,
  HEIGHT: 1080,

  BRICK_COLS: 10,
  BRICK_ROWS: 10,
  BRICK_WIDTH: 150,
  BRICK_HEIGHT: 60,
  BRICK_OFFSET_X: 200,
  BRICK_OFFSET_Y: 0,
  BRICK_SPACING_X: 155,
  BRICK_SPACING_Y: 65,

  PADDLE_WIDTH: 250,
  PADDLE_HEIGHT: 50,
  PADDLE_Y: 1000,
  // p5 code uses 22 units per 60fps frame; we keep the same feel.
  PADDLE_SPEED_PER_FRAME: 22,

  BALL_DIAMETER: 38,
  BALL_RADIUS: 19,
  BALL_START_VX_PER_FRAME: 5,
  BALL_START_VY_PER_FRAME: -5,

  BALL_SPEEDUP_PER_BRICK_HIT: 0.45,
  BALL_MAX_SPEED_PER_FRAME: 24,
  BALL_STRENGTH_TIER2_SPEED: 12,
  BALL_STRENGTH_TIER3_SPEED: 18,

  CAUGHT_TRAJECTORY_LENGTH: 260,
  CAUGHT_AIM_ANGLE_OFFSET: 0.2,
  CAUGHT_RELEASE_SPEED_PER_FRAME: 13,

  POWERUP_DROP_CHANCE: 0.22,
  POWERUP_RADIUS: 26,
  POWERUP_FALL_SPEED_PER_FRAME: 7,

  MULTIBALL_EXTRA_BALLS: 1,
  MULTIBALL_SPREAD_VX_PER_FRAME: 6,

  LASER_SHOTS_PER_PICKUP: 10,
  LASER_COOLDOWN_SECONDS: 0.12,
  LASER_SHOT_WIDTH: 18,
  LASER_SHOT_HEIGHT: 56,
  LASER_SHOT_SPEED_PER_FRAME: -26,

  GRAVITY_WELL_DURATION_SECONDS: 7,
  GRAVITY_WELL_RADIUS: 42,
  GRAVITY_WELL_STRENGTH: 5200,
  GRAVITY_WELL_SOFTENING: 9000,
});
